Delete features and little burg fixes.
Needlinc/Needlinc pull request #38
Opened 2024-02-01 16:44 UTC by XRichardroidX

Add delete home page and market place feature in profile
Implemented Deleting of user account feature from settings
Fix long waiting time for comment to clear after a post request to the database

2024-02-01 21:13 UTC, Victor-chiemerie requested changes
# Required changes

Excellent work but please take note of the review given

2024-02-01 21:13 UTC, Victor-chiemerie commented on lib/needlinc/shared-pages/edit-profile.dart
> +                                              phoneNumber: "+234${phoneNumberController.text}",
This part didn't let me put my phone number in full, and it didn't quite tell me not to add the first Zero

2024-02-01 21:13 UTC, Victor-chiemerie commented on lib/needlinc/shared-pages/news.dart
> +                                          },
Supposed to be an option to delete

2024-02-02 20:27 UTC, XRichardroidX commented on lib/needlinc/shared-pages/edit-profile.dart
> +                                              phoneNumber: "+234${phoneNumberController.text}",
This is a UI issue, I will need someone in charge of the Ui design to handle it, so that users can see that the +234 format is the one to be used.

2024-02-02 20:28 UTC, XRichardroidX commented on lib/needlinc/shared-pages/auth-pages/sign-in.dart
> +                                         // showSnackBar(context, '$error');
The user will get error messages if anything is wrong when the system tries to authenticate them, that one was unnecessary.

2024-02-02 20:31 UTC, XRichardroidX commented on lib/needlinc/shared-pages/auth-pages/welcome.dart
> +              width: screenHeight,
Thank you for that, I will need you to fix the size, someone complained it was too big.

2024-02-02 20:31 UTC, XRichardroidX commented on lib/needlinc/business-pages/profile.dart
>                            },
Thanks for that, I have fixed it now.

2024-02-02 20:31 UTC, XRichardroidX commented on lib/needlinc/business-pages/profile.dart
>                          },
Thanks for that, I have fixed it now.

2024-02-03 11:38 UTC, Victor-chiemerie commented on lib/needlinc/shared-pages/auth-pages/sign-in.dart
> +                                         // showSnackBar(context, '$error');
Chiza tried to skip the `Upload Profile picture feature` by clicking next
Nothing was happening and she wasn't able to proceed until i had to explain to her that it can't be skipped and why
Therefore, the error message there didn't show

2024-02-04 06:27 UTC, XRichardroidX commented on lib/needlinc/shared-pages/auth-pages/sign-in.dart
> +                                         // showSnackBar(context, '$error');
The message that will tell you to pick an image for your profile picture is not an error message, I kept that one as a warning so it probably displayed but she didn't read the text below.

2024-02-04 06:27 UTC, merged